replace 'yihui/hugo-lithium-theme' with 'yihui/hugo-lithium'
When I run `blogdown::new_site()` with the default `theme = "yihui/hugo-lithium-theme"`, I get an error:
```
Rendering content/post/2015-07-23-r-rmarkdown.Rmd
Error: Unable to find theme Directory: /Users/rnolan/Dropbox/R/blog/themes/hugo-lithium-theme

Serving the directory /Users/rnolan/Dropbox/R/blog at http://127.0.0.1:5641
To stop the server, run servr::daemon_stop("4326078320") or restart your R session
Error in setwd(site.dir) : cannot change working directory
```
However I notice that even though there's no `/Users/rnolan/Dropbox/R/blog/themes/hugo-lithium-theme`, there is a `/Users/rnolan/Dropbox/R/blog/themes/hugo-lithium`. For reasons that I don't fully understand, when I run `blogdown::new_site(theme = "yihui/hugo-lithium-theme")`, everything works fine. This may be because https://github.com/yihui/hugo-lithium-theme redirects to https://github.com/yihui/hugo-lithium, but I don't know. In any case, https://github.com/yihui/hugo-lithium seems to be in working order and I think it should all work fine with that as the new default.
Thanks Yihui and other authors and maintainers, your work makes our lives easier :)